vlans:
  "default": "1"
  "second": "2"

dns_domain: example.com

dhcp_networks:
  default:
    subnets:
      "1.2.3.0/24":
  second:
    subnets:
      "2.2.3.4":
        netmask: 255.255.255.0

network_nodes:
  host1:
    networks:
      if1:
        hwaddr: 00:16:3e:81:5a:d1
        ipv4: 1.2.3.9/24
      if2:
        hwaddr: 00:16:3e:81:5a:d2
        ipv4: 2.2.3.9/24
        vlan: second
