- set_fact:
    _prefixes:
      - "{{tftpboot_directory}}"

- set_fact:
    _prefixes: "{{ _prefixes  + [ uefi_http_boot_directory ] }}"
  when: uefi_http_boot_directory is defined

- name: create target directory
  file:
    state: directory
    path: "{{_prefix}}/{{_os_entry.value.linuxefi.path|dirname}}"
  loop_control:
    loop_var: _prefix
  with_items: "{{_prefixes}}"

- name: copy kernel (http)
  get_url:
    url: "{{_os_entry.value.linuxefi.source}}"
    dest: "{{_prefix}}/{{_os_entry.value.linuxefi.path}}"
    mode: 0644
    owner: root
  when: _os_entry.value.linuxefi.source is defined and _os_entry.value.linuxefi.source.startswith("http")
  with_items: "{{_prefixes}}"
  loop_control:
    loop_var: _prefix

- name: copy kernel (local)
  copy:
    remote_src: yes
    src: "{{_os_entry.value.linuxefi.source}}"
    dest: "{{_prefix}}/{{_os_entry.value.linuxefi.path}}"
    mode: 0644
    owner: root
  when: _os_entry.value.linuxefi.source is defined and not _os_entry.value.linuxefi.source.startswith("http")
  with_items: "{{_prefixes}}"
  loop_control:
    loop_var: _prefix

- name: copy initrd (http)
  get_url:
    url: "{{_os_entry.value.initrdefi.source}}"
    dest: "{{_prefix}}/{{_os_entry.value.initrdefi.path}}"
    mode: 0644
    owner: root
  when: _os_entry.value.initrdefi.source is defined and _os_entry.value.initrdefi.source.startswith("http")
  with_items: "{{_prefixes}}"
  loop_control:
    loop_var: _prefix

- name: copy initrd (local)
  copy:
    remote_src: yes
    src: "{{_os_entry.value.initrdefi.source}}"
    dest: "{{_prefix}}/{{_os_entry.value.initrdefi.path}}"
    mode: 0644
    owner: root
  when: _os_entry.value.initrdefi.source is defined and not _os_entry.value.initrdefi.source.startswith("http")
  with_items: "{{_prefixes}}"
  loop_control:
    loop_var: _prefix
