- set_fact:
    role_packages:
      - dhcp-server

  when: ansible_os_family == "Suse"


- include_role:
    name: basic-host
    tasks_from: install_packages

- name: update dhcpd configuration
  template:
    src: dhcpd.conf.j2
    dest: "{{dhcpd_isc_conf | default('/etc/dhcp/dhcpd.conf')}}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart dhcpd

- name: configure firewall
  firewalld:
    service: dhcp
    permanent: true
    state: enabled
    immediate: true
  when: ansible_os_family == "RedHat"

- name: enable dhcpd
  service: name=dhcpd enabled=yes