- name: print information about the current ansible version
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - debug:
        msg:
          - "Ansible version: {{ansible_version.full}}"
          - "Virtualization: {{ansible_virtualization_role}}"
          - "Virtualization type: {{ansible_virtualization_type}}"
          - "Home: {{lookup('ansible.builtin.env', 'HOME')}}"
    - name: save inventory variables before test overrides
      set_fact:
        _inventory_vlans: "{{vlans | default({})}}"
        _inventory_dhcp_networks: "{{dhcp_networks | default({})}}"
        _inventory_network_nodes: "{{network_nodes | default({})}}"
        _inventory_dns_domain: "{{dns_domain | default('')}}"
    - name: clone data-utilities
      ansible.builtin.git:
        repo: https://github.com/aardsoft/ansible-data-utilities.git
        dest: roles/data-utilities
    - name: set default variables
      set_fact:
        dhcp_user: "{{ansible_facts.user_uid}}"
        dhcp_group: "{{ansible_facts.user_gid}}"
        dhcpd_isc_conf: /dhcpd.conf

# test an almost empty dhcp definition, with no subnets defined
- name: test 1
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    config_prefix: test_results/test1
  pre_tasks:
    - name: load environment
      include_vars:
        file: test1.yml
  roles:
    - role: ../

# this restores the variables configured by the inventory plugin.
# the data in the vars is now ignored, but we use the pre-parsed
# inventory data
- name: test 2
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    config_prefix: test_results/test2
  pre_tasks:
    - name: restore inventory variables
      set_fact:
        vlans: "{{_inventory_vlans}}"
        dhcp_networks: "{{_inventory_dhcp_networks}}"
        network_nodes: "{{_inventory_network_nodes}}"
        dns_domain: "{{_inventory_dns_domain}}"
  roles:
    - role: ../

# this now overrides the inventory data with subnet definitions from the
# variables. The result is pretty much identical to the first test - due
# to the missing pre-parsed additional data the role skips pretty much all
# of it.
# TODO: add a 4th test with manual preparsed data
- name: test 3
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    config_prefix: test_results/test3
  pre_tasks:
    - name: load environment
      include_vars:
        file: test3.yml
  roles:
    - role: ../

- name: check for changed test files
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - ansible.builtin.shell: |
        git status --porcelain|grep test_results
      register: git_status
      ignore_errors: true
    - ansible.builtin.fail:
        msg: "Changes to test results found, fix config generation or commit changes"
      when: git_status.stdout != ""
