name: Build role specific container

on:
  push:
    branches:
      - master
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    uses: aardsoft/ansible-data-utilities/.github/workflows/build-role-container.yml@master
    with:
      extra-architectures: aarch64
      extra-repositories: https://download.opensuse.org/update/leap/15.6/oss/
